import { test } from 'node:test';
import assert from 'node:assert/strict';
import BN from 'bn.js';
import { PublicKey } from '@solana/web3.js';
import { DYNAMIC_BONDING_CURVE_PROGRAM_ID, type PoolConfig, type VirtualPool } from '@meteora-ag/dynamic-bonding-curve-sdk';
import { inspect, summarize, formatAmount, type MintEvidence } from '../server/engine.js';
import { validateAddress, assertDbcAccount, normalize, boundedFetch } from '../server/reader.js';

const bn = (n: number) => new BN(n);
const key = new PublicKey('11111111111111111111111111111111');
function fixture() {
  const vesting = { isInitialized: 0, vestingPercentage: 0, bpsPerPeriod: 10000, numberOfPeriods: 1, frequency: 1, cliffDurationFromMigrationTime: 86400 };
  const config = { poolFees: { baseFee: { cliffFeeNumerator: bn(2500000), baseFeeMode: 0, firstFactor: 0, secondFactor: bn(0), thirdFactor: bn(0) }, dynamicFee: { initialized: 0, maxVolatilityAccumulator: 100, variableFeeControl: 100, binStep: 1 } }, partnerPermanentLockedLiquidityPercentage: 100, creatorPermanentLockedLiquidityPercentage: 0, partnerLiquidityPercentage: 0, creatorLiquidityPercentage: 0, partnerLiquidityVestingInfo: { ...vesting }, creatorLiquidityVestingInfo: { ...vesting }, lockedVestingConfig: { amountPerPeriod: bn(0), numberOfPeriod: bn(0), cliffUnlockAmount: bn(0), frequency: bn(0), cliffDurationFromMigrationTime: bn(0) }, preMigrationTokenSupply: bn(1000), postMigrationTokenSupply: bn(1000), swapBaseAmount: bn(900), migrationBaseThreshold: bn(100), leftoverReceiver: key, fixedTokenSupplyFlag: 1, tokenUpdateAuthority: 1, curve: [{ sqrtPrice: bn(2), liquidity: bn(100) }, { sqrtPrice: bn(999999999), liquidity: bn(100) }, { sqrtPrice: bn(0), liquidity: bn(0) }], sqrtStartPrice: bn(1), migrationSqrtPrice: bn(2), migrationQuoteThreshold: bn(100), migrationOption: 1, creatorTradingFeePercentage: 10, migrationFeePercentage: 0, migratedPoolFeeBps: 10 } as PoolConfig;
  const pool = { quoteReserve: bn(50), isMigrated: 0, migrationProgress: 0 } as VirtualPool['poolState'];
  const mint: MintEvidence = { supply: '1000', decimals: 0, mintAuthority: null, freezeAuthority: null, extensions: [], extensionReadComplete: true };
  return { config, pool, mint };
}
test('unknown authority coverage never establishes safety', () => { const f = fixture(); const result = inspect(f.config, f.pool, null, 9); assert.equal(summarize(result.checks).verdict, 'Assessment incomplete'); assert.equal(summarize(result.checks).coverage, 63); });
test('fee numerator denominator is 1e9, not 10000', () => { const f = fixture(); assert.equal(inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'fees')?.evidence.maxBps, 25); });
test('rate limiter includes possible 99% ceiling', () => { const f = fixture(); Object.assign(f.config.poolFees.baseFee, { baseFeeMode: 2, firstFactor: 1, secondFactor: bn(1), thirdFactor: bn(1) }); const check = inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'fees'); assert.equal(check?.evidence.maxBps, 9900); assert.equal(check?.status, 'risk'); });
test('dynamic fee ceiling adds volatility maximum and respects cap', () => { const f = fixture(); Object.assign(f.config.poolFees.dynamicFee, { initialized: 1, maxVolatilityAccumulator: 10000000, variableFeeControl: 10000000, binStep: 100 }); assert.equal(inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'fees')?.evidence.maxBps, 9900); });
test('six LP buckets include vesting; majority unlocked is risk', () => { const f = fixture(); f.config.partnerPermanentLockedLiquidityPercentage = 0; f.config.creatorLiquidityPercentage = 89; Object.assign(f.config.creatorLiquidityVestingInfo, { isInitialized: 1, vestingPercentage: 11 }); const c = inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'liquidity'); assert.equal(c?.evidence.allocationTotal, 100); assert.equal(c?.status, 'risk'); });
test('SDK vesting rounding cannot turn 50% liquid allocation into majority risk', () => { const f = fixture(); f.config.partnerPermanentLockedLiquidityPercentage = 0; f.config.creatorLiquidityPercentage = 50; Object.assign(f.config.creatorLiquidityVestingInfo, { isInitialized: 1, vestingPercentage: 50 }); const c = inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'liquidity'); assert.equal(c?.evidence.configuredLiquidAllocationPercent, 50); assert.equal(c?.status, 'caution'); });
test('graduation price ignores terminal curve sentinel and padding', () => { const f = fixture(); const c = inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'curve'); assert.equal(c?.status, 'pass'); assert.equal(c?.evidence.amplification, '4.0000'); assert.equal(c?.evidence.activeSegments, 2); });
test('100% reserve is not migrated without migrated flag', () => { const f = fixture(); f.pool.quoteReserve = new BN('18446744073709551615'); const r = inspect(f.config, f.pool, f.mint, 9); assert.equal(r.migration.percent, 100); assert.match(r.migration.status, /pending/); });
test('unknown extension is unknown; permissioned burn needs review', () => { const f = fixture(); f.mint.extensions = ['Unknown(99)']; assert.equal(inspect(f.config, f.pool, f.mint, 9).checks[2].status, 'unknown'); f.mint.extensions = ['PermissionedBurn']; assert.equal(inspect(f.config, f.pool, f.mint, 9).checks[2].status, 'caution'); });
test('liquid leftover allocation is not silently passed', () => { const f = fixture(); f.config.postMigrationTokenSupply = bn(2000); const c = inspect(f.config, f.pool, f.mint, 9).checks.find(c => c.id === 'allocation'); assert.equal(c?.evidence.configuredLeftoverEstimateRaw, '1000'); assert.equal(c?.status, 'caution'); });
test('mint and freeze capabilities produce known risks', () => { const f = fixture(); f.mint.mintAuthority = key.toBase58(); f.mint.freezeAuthority = key.toBase58(); assert.equal(summarize(inspect(f.config, f.pool, f.mint, 9).checks).verdict, 'Known risk detected'); });
test('invalid addresses and non DBC accounts are rejected', () => { assert.throws(() => validateAddress('bad')); assert.throws(() => validateAddress(['bad'])); assert.throws(() => assertDbcAccount(null)); assert.throws(() => assertDbcAccount({ owner: key, executable: false, data: Buffer.alloc(100), lamports: 0 })); assert.throws(() => assertDbcAccount({ owner: DYNAMIC_BONDING_CURVE_PROGRAM_ID, executable: false, data: Buffer.alloc(4), lamports: 0 })); });
test('raw report BN data is decimal, not SDK hex JSON', () => { assert.deepEqual(normalize({ amount: new BN('1000000000000000000'), key }), { amount: '1000000000000000000', key: key.toBase58() }); assert.equal(formatAmount('11530000000', 9), '11.53'); });
test('RPC body size bound rejects oversized upstream response', async () => { const original = globalThis.fetch; globalThis.fetch = async () => new Response('x', { headers: { 'content-length': '2000000' } }); try { await assert.rejects(() => boundedFetch('https://example.test'), /too large/); } finally { globalThis.fetch = original; } });
