import { test } from 'node:test';
import assert from 'node:assert/strict';
import BN from 'bn.js';
import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { createDbcProgram, deriveDbcPoolAddress, DYNAMIC_BONDING_CURVE_PROGRAM_ID } from '@meteora-ag/dynamic-bonding-curve-sdk';
import { MintLayout, TOKEN_PROGRAM_ID, TOKEN_2022_PROGRAM_ID } from '@solana/spl-token';
import { readReport, InvalidAccountError } from '../server/reader.js';

type LayoutType = string | { array?: [LayoutType, number]; defined?: { name: string }; option?: LayoutType };
interface LayoutDefinition { name: string; type: { kind: string; fields?: { name: string; type: LayoutType }[] } }
const { program } = createDbcProgram(new Connection('http://127.0.0.1:1'));
// Anchor's convenience encoder allocates only1000 bytes; DBC config exceeds it.
// Use the exact SDK-built IDL layout with a sufficiently sized fixture buffer.
const layouts = (program.coder.accounts as unknown as { accountLayouts: Map<string, { discriminator: number[]; layout: { encode(value: unknown, buffer: Buffer): number } }> }).accountLayouts;
program.coder.accounts.encode = async (name, value) => { const entry = layouts.get(name)!; const buffer = Buffer.alloc(65536); const length = entry.layout.encode(value, buffer); return Buffer.concat([Buffer.from(entry.discriminator), buffer.subarray(0, length)]); };
const definitions = program.idl.types as unknown as LayoutDefinition[];
function blank(type: LayoutType): unknown {
  if (typeof type === 'string') { if (type === 'pubkey') return PublicKey.default; if (type === 'bool') return false; if (type === 'string') return ''; return /^(u|i)(64|128|256)$/.test(type) ? new BN(0) : 0; }
  if (type.array) return Array.from({ length: type.array[1] }, () => blank(type.array![0]));
  if (type.option) return null;
  const definition = definitions.find(d => d.name === type.defined?.name);
  if (!definition?.type.fields) throw new Error(`Unsupported fixture type ${JSON.stringify(type)}`);
  return Object.fromEntries(definition.type.fields.map(field => [field.name, blank(field.type)]));
}
function state(name: string): Record<string, unknown> { return blank({ defined: { name } }) as Record<string, unknown>; }
async function fixture(hook = false) {
  const configKey = Keypair.generate().publicKey; const baseMint = Keypair.generate().publicKey; const quoteMint = Keypair.generate().publicKey;
  const config = state('poolConfig'); Object.assign(config, { quoteMint, swapBaseAmount: new BN(900), migrationBaseThreshold: new BN(100), migrationQuoteThreshold: new BN(100), preMigrationTokenSupply: new BN(1000), postMigrationTokenSupply: new BN(1000), fixedTokenSupplyFlag: 1, partnerPermanentLockedLiquidityPercentage: 100, sqrtStartPrice: new BN(1), migrationSqrtPrice: new BN(2), migrationOption: 1 });
  const curve = config.curve as Record<string, unknown>[]; Object.assign(curve[0], { sqrtPrice: new BN(2), liquidity: new BN(100) });
  const pool = state('poolState'); Object.assign(pool, { config: configKey, baseMint, quoteReserve: new BN(50) });
  const poolAddress = deriveDbcPoolAddress(quoteMint, baseMint, configKey).toBase58();
  const poolName = hook ? 'transferHookPool' : 'virtualPool'; const configName = hook ? 'configWithTransferHook' : 'poolConfig';
  const hookProgram = Keypair.generate().publicKey;
  const hookConfig = { ...state('configWithTransferHook'), config, transferHookProgram: hookProgram };
  const poolData = await program.coder.accounts.encode(poolName, { poolState: pool });
  const configData = await program.coder.accounts.encode(configName, hook ? hookConfig : config);
  const mintData = Buffer.alloc(MintLayout.span); MintLayout.encode({ mintAuthorityOption: 0, mintAuthority: PublicKey.default, supply: BigInt(1000), decimals: 9, isInitialized: true, freezeAuthorityOption: 0, freezeAuthority: PublicKey.default }, mintData);
  const rpcAccount = (data: Buffer, owner = DYNAMIC_BONDING_CURVE_PROGRAM_ID) => ({ data: [data.toString('base64'), 'base64'], owner: owner.toBase58(), executable: false, lamports: 10000, rentEpoch: 0, space: data.length });
  const accounts = new Map<string, ReturnType<typeof rpcAccount> | null>([[poolAddress, rpcAccount(poolData)], [configKey.toBase58(), rpcAccount(configData)], [baseMint.toBase58(), rpcAccount(mintData, TOKEN_PROGRAM_ID)], [quoteMint.toBase58(), rpcAccount(mintData, TOKEN_PROGRAM_ID)]]);
  let mintFailure = false;
  const fetchImpl: typeof fetch = async (_input, init) => { const request = JSON.parse(String(init?.body)); if (mintFailure && request.method === 'getMultipleAccounts') throw new Error('RPC offline'); const value = request.method === 'getAccountInfo' ? accounts.get(request.params[0]) ?? null : request.params[0].map((key: string) => accounts.get(key) ?? null); return new Response(JSON.stringify({ jsonrpc: '2.0', id: request.id, result: { context: { slot: 123 }, value } }), { headers: { 'content-type': 'application/json' } }); };
  return { accounts, configKey, baseMint, quoteMint, poolAddress, pool, config, configData, poolData, mintData, rpcAccount, fetchImpl, hookProgram, failMints() { mintFailure = true; } };
}
for (const hook of [false, true]) test(`${hook ? 'transfer-hook' : 'standard'} IDL encoded family reads end to end with provenance`, async () => { const f = await fixture(hook); const report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.checks.length, 8); assert.equal(report.synthetic, false); assert.equal(report.slot, 123); const raw = report.raw as Record<string, unknown>; assert.equal(raw.poolFamily, hook ? 'transferHookPool' : 'virtualPool'); assert.equal(raw.configFamily, hook ? 'configWithTransferHook' : 'poolConfig'); assert.equal(raw.mintSlot, 123); assert.equal(raw.transferHookProgram, hook ? f.hookProgram.toBase58() : null); });
test('mismatched pool/config account families are rejected', async () => { const f = await fixture(true); const data = await program.coder.accounts.encode('poolConfig', f.config); f.accounts.set(f.configKey.toBase58(), f.rpcAccount(data)); await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }), InvalidAccountError); });
test('unsupported pool discriminator and malformed config are rejected', async () => { const f = await fixture(); f.accounts.set(f.poolAddress, f.rpcAccount(Buffer.alloc(16, 99))); await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }), /discriminator/); f.accounts.set(f.poolAddress, f.rpcAccount(f.poolData)); f.accounts.set(f.configKey.toBase58(), f.rpcAccount(f.configData.subarray(0, 10))); await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }), /layout/); });
test('valid owner/layout with incorrect canonical PDA is rejected', async () => { const f = await fixture(); const wrong = Keypair.generate().publicKey.toBase58(); f.accounts.set(wrong, f.accounts.get(f.poolAddress)!); await assert.rejects(() => readReport(wrong, 'devnet', { fetchImpl: f.fetchImpl }), /PDA/); });
test('missing and uninitialized base mints preserve partial report with unknown checks', async () => { const f = await fixture(); f.accounts.set(f.baseMint.toBase58(), null); let report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.deepEqual(report.checks.slice(0, 3).map(c => c.status), ['unknown', 'unknown', 'unknown']); const uninitialized = Buffer.from(f.mintData); uninitialized[45] = 0; f.accounts.set(f.baseMint.toBase58(), f.rpcAccount(uninitialized, TOKEN_PROGRAM_ID)); report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.coverage, 63); });
test('mint RPC failure preserves partial assessment and provenance', async () => { const f = await fixture(); f.failMints(); const report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.coverage, 63); assert.match((report.raw as Record<string, string>).mintReadError, /RPC/); assert.equal((report.raw as Record<string, unknown>).mintSlot, null); });
test('unknown and malformed Token2022 TLV never receive no-flag policy summary', async () => { const f = await fixture(); const extended = Buffer.alloc(170); f.mintData.copy(extended); extended[165] = 1; extended.writeUInt16LE(99, 166); extended.writeUInt16LE(0, 168); f.accounts.set(f.baseMint.toBase58(), f.rpcAccount(extended, TOKEN_2022_PROGRAM_ID)); let report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.checks[2].status, 'unknown'); assert.match(report.checks[2].summary, /unknown/i); extended.writeUInt16LE(1000, 168); f.accounts.set(f.baseMint.toBase58(), f.rpcAccount(extended, TOKEN_2022_PROGRAM_ID)); report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.checks[2].status, 'unknown'); assert.equal(report.checks[2].evidence.extensionReadComplete, false); });
test('legacy migration destination and pending versus migrated flags survive decode', async () => { const f = await fixture(); Object.assign(f.config, { migrationOption: 0 }); Object.assign(f.pool, { quoteReserve: new BN(100), isMigrated: 0 }); f.accounts.set(f.configKey.toBase58(), f.rpcAccount(await program.coder.accounts.encode('poolConfig', f.config))); f.accounts.set(f.poolAddress, f.rpcAccount(await program.coder.accounts.encode('virtualPool', { poolState: f.pool }))); let report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.migration.destination, 'DAMM v1'); assert.match(report.migration.status, /pending/); f.pool.isMigrated = 1; f.accounts.set(f.poolAddress, f.rpcAccount(await program.coder.accounts.encode('virtualPool', { poolState: f.pool }))); report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.migration.status, 'Migrated'); });
test('reader timeout and caller cancellation abort actual fetch path', async () => { const f = await fixture(); const hanging: typeof fetch = async (_input, init) => new Promise((_resolve, reject) => { init?.signal?.addEventListener('abort', () => reject(init.signal!.reason), { once: true }); }); const keepAlive = setInterval(() => {}, 1000); try { await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: hanging, timeoutMs: 15 }), /timeout|aborted/i); const controller = new AbortController(); const reading = readReport(f.poolAddress, 'devnet', { fetchImpl: hanging, signal: controller.signal }); controller.abort(new Error('Client cancelled')); await assert.rejects(() => reading, /cancelled/); } finally { clearInterval(keepAlive); } });
