import { test } from 'node:test';
import assert from 'node:assert/strict';
import BN from 'bn.js';
import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { createDbcProgram, deriveDbcPoolAddress, DYNAMIC_BONDING_CURVE_PROGRAM_ID } from '@meteora-ag/dynamic-bonding-curve-sdk';
import { MintLayout, TOKEN_PROGRAM_ID, TOKEN_2022_PROGRAM_ID } from '@solana/spl-token';
import { readReport, InvalidAccountError, rpcCall, boundedFetch, RpcScheduler, RpcTransportError, retryAfterSeconds, withRpcRetries } from '../server/reader.js';

type LayoutType = string | { array?: [LayoutType, number]; defined?: { name: string }; option?: LayoutType };
interface LayoutDefinition { name: string; type: { kind: string; fields?: { name: string; type: LayoutType }[] } }
const { program } = createDbcProgram(new Connection('http://127.0.0.1:1'));
// Anchor's convenience encoder allocates only1000 bytes; DBC config exceeds it.
// Use the exact SDK-built IDL layout with a sufficiently sized fixture buffer.
const layouts = (program.coder.accounts as unknown as { accountLayouts: Map<string, { discriminator: number[]; layout: { encode(value: unknown, buffer: Buffer): number } }> }).accountLayouts;
program.coder.accounts.encode = async (name, value) => { const entry = layouts.get(name)!; const buffer = Buffer.alloc(65536); const length = entry.layout.encode(value, buffer); return Buffer.concat([Buffer.from(entry.discriminator), buffer.subarray(0, length)]); };
const definitions = program.idl.types as unknown as LayoutDefinition[];
function blank(type: LayoutType): unknown {
  if (typeof type === 'string') { if (type === 'pubkey') return PublicKey.default; if (type === 'bool') return false; if (type === 'string') return ''; return /^(u|i)(64|128|256)$/.test(type) ? new BN(0) : 0; }
  if (type.array) return Array.from({ length: type.array[1] }, () => blank(type.array![0]));
  if (type.option) return null;
  const definition = definitions.find(d => d.name === type.defined?.name);
  if (!definition?.type.fields) throw new Error(`Unsupported fixture type ${JSON.stringify(type)}`);
  return Object.fromEntries(definition.type.fields.map(field => [field.name, blank(field.type)]));
}
function state(name: string): Record<string, unknown> { return blank({ defined: { name } }) as Record<string, unknown>; }
async function fixture(hook = false) {
  const configKey = Keypair.generate().publicKey; const baseMint = Keypair.generate().publicKey; const quoteMint = Keypair.generate().publicKey;
  const config = state('poolConfig'); Object.assign(config, { quoteMint, swapBaseAmount: new BN(900), migrationBaseThreshold: new BN(100), migrationQuoteThreshold: new BN(100), preMigrationTokenSupply: new BN(1000), postMigrationTokenSupply: new BN(1000), fixedTokenSupplyFlag: 1, partnerPermanentLockedLiquidityPercentage: 100, sqrtStartPrice: new BN(1), migrationSqrtPrice: new BN(2), migrationOption: 1 });
  const curve = config.curve as Record<string, unknown>[]; Object.assign(curve[0], { sqrtPrice: new BN(2), liquidity: new BN(100) });
  const pool = state('poolState'); Object.assign(pool, { config: configKey, baseMint, quoteReserve: new BN(50) });
  const poolAddress = deriveDbcPoolAddress(quoteMint, baseMint, configKey).toBase58();
  const poolName = hook ? 'transferHookPool' : 'virtualPool'; const configName = hook ? 'configWithTransferHook' : 'poolConfig';
  const hookProgram = Keypair.generate().publicKey;
  const hookConfig = { ...state('configWithTransferHook'), config, transferHookProgram: hookProgram };
  const poolData = await program.coder.accounts.encode(poolName, { poolState: pool });
  const configData = await program.coder.accounts.encode(configName, hook ? hookConfig : config);
  const mintData = Buffer.alloc(MintLayout.span); MintLayout.encode({ mintAuthorityOption: 0, mintAuthority: PublicKey.default, supply: BigInt(1000), decimals: 9, isInitialized: true, freezeAuthorityOption: 0, freezeAuthority: PublicKey.default }, mintData);
  const rpcAccount = (data: Buffer, owner = DYNAMIC_BONDING_CURVE_PROGRAM_ID) => ({ data: [data.toString('base64'), 'base64'], owner: owner.toBase58(), executable: false, lamports: 10000, rentEpoch: 0, space: data.length });
  const accounts = new Map<string, ReturnType<typeof rpcAccount> | null>([[poolAddress, rpcAccount(poolData)], [configKey.toBase58(), rpcAccount(configData)], [baseMint.toBase58(), rpcAccount(mintData, TOKEN_PROGRAM_ID)], [quoteMint.toBase58(), rpcAccount(mintData, TOKEN_PROGRAM_ID)]]);
  let mintFailure = false;
  const fetchImpl: typeof fetch = async (_input, init) => { const request = JSON.parse(String(init?.body)); if (mintFailure && request.method === 'getMultipleAccounts') throw new Error('RPC offline'); const value = request.method === 'getAccountInfo' ? accounts.get(request.params[0]) ?? null : request.params[0].map((key: string) => accounts.get(key) ?? null); return new Response(JSON.stringify({ jsonrpc: '2.0', id: request.id, result: { context: { slot: 123 }, value } }), { headers: { 'content-type': 'application/json' } }); };
  return { accounts, configKey, baseMint, quoteMint, poolAddress, pool, config, configData, poolData, mintData, rpcAccount, fetchImpl, hookProgram, failMints() { mintFailure = true; } };
}
for (const hook of [false, true]) test(`${hook ? 'transfer-hook' : 'standard'} IDL encoded family reads end to end with provenance`, async () => { const f = await fixture(hook); const report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.checks.length, 8); assert.equal(report.synthetic, false); assert.equal(report.slot, 123); const raw = report.raw as Record<string, unknown>; assert.equal(raw.poolFamily, hook ? 'transferHookPool' : 'virtualPool'); assert.equal(raw.configFamily, hook ? 'configWithTransferHook' : 'poolConfig'); assert.equal(raw.mintSlot, 123); assert.equal(raw.transferHookProgram, hook ? f.hookProgram.toBase58() : null); });
test('mismatched pool/config account families are rejected', async () => { const f = await fixture(true); const data = await program.coder.accounts.encode('poolConfig', f.config); f.accounts.set(f.configKey.toBase58(), f.rpcAccount(data)); await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }), InvalidAccountError); });
test('unsupported pool discriminator and malformed config are rejected', async () => { const f = await fixture(); f.accounts.set(f.poolAddress, f.rpcAccount(Buffer.alloc(16, 99))); await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }), /discriminator/); f.accounts.set(f.poolAddress, f.rpcAccount(f.poolData)); f.accounts.set(f.configKey.toBase58(), f.rpcAccount(f.configData.subarray(0, 10))); await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }), /layout/); });
test('valid owner/layout with incorrect canonical PDA is rejected', async () => { const f = await fixture(); const wrong = Keypair.generate().publicKey.toBase58(); f.accounts.set(wrong, f.accounts.get(f.poolAddress)!); await assert.rejects(() => readReport(wrong, 'devnet', { fetchImpl: f.fetchImpl }), /PDA/); });
test('missing and uninitialized base mints preserve partial report with unknown checks', async () => { const f = await fixture(); f.accounts.set(f.baseMint.toBase58(), null); let report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.deepEqual(report.checks.slice(0, 3).map(c => c.status), ['unknown', 'unknown', 'unknown']); const uninitialized = Buffer.from(f.mintData); uninitialized[45] = 0; f.accounts.set(f.baseMint.toBase58(), f.rpcAccount(uninitialized, TOKEN_PROGRAM_ID)); report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.coverage, 63); });
test('mint RPC failure preserves partial assessment and provenance', async () => { const f = await fixture(); f.failMints(); const report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.coverage, 63); assert.match((report.raw as Record<string, string>).mintReadError, /RPC/); assert.equal((report.raw as Record<string, unknown>).mintSlot, null); });
test('unknown and malformed Token2022 TLV never receive no-flag policy summary', async () => { const f = await fixture(); const extended = Buffer.alloc(170); f.mintData.copy(extended); extended[165] = 1; extended.writeUInt16LE(99, 166); extended.writeUInt16LE(0, 168); f.accounts.set(f.baseMint.toBase58(), f.rpcAccount(extended, TOKEN_2022_PROGRAM_ID)); let report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.checks[2].status, 'unknown'); assert.match(report.checks[2].summary, /unknown/i); extended.writeUInt16LE(1000, 168); f.accounts.set(f.baseMint.toBase58(), f.rpcAccount(extended, TOKEN_2022_PROGRAM_ID)); report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.checks[2].status, 'unknown'); assert.equal(report.checks[2].evidence.extensionReadComplete, false); });
test('legacy migration destination and pending versus migrated flags survive decode', async () => { const f = await fixture(); Object.assign(f.config, { migrationOption: 0 }); Object.assign(f.pool, { quoteReserve: new BN(100), isMigrated: 0 }); f.accounts.set(f.configKey.toBase58(), f.rpcAccount(await program.coder.accounts.encode('poolConfig', f.config))); f.accounts.set(f.poolAddress, f.rpcAccount(await program.coder.accounts.encode('virtualPool', { poolState: f.pool }))); let report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.migration.destination, 'DAMM v1'); assert.match(report.migration.status, /pending/); f.pool.isMigrated = 1; f.accounts.set(f.poolAddress, f.rpcAccount(await program.coder.accounts.encode('virtualPool', { poolState: f.pool }))); report = await readReport(f.poolAddress, 'devnet', { fetchImpl: f.fetchImpl }); assert.equal(report.migration.status, 'Migrated'); });
test('reader timeout and caller cancellation abort actual fetch path', async () => { const f = await fixture(); const hanging: typeof fetch = async (_input, init) => new Promise((_resolve, reject) => { init?.signal?.addEventListener('abort', () => reject(init.signal!.reason), { once: true }); }); const keepAlive = setInterval(() => {}, 1000); try { await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: hanging, timeoutMs: 15 }), /timeout|timed out|aborted/i); const controller = new AbortController(); const reading = readReport(f.poolAddress, 'devnet', { fetchImpl: hanging, signal: controller.signal }); controller.abort(new Error('Client cancelled')); await assert.rejects(() => reading, /cancelled/); } finally { clearInterval(keepAlive); } });
test('transient HTTP failure retries one endpoint then falls back with consistent whole-account reads', async () => { const f = await fixture(); const previous = process.env.DEVNET_RPC_URLS; process.env.DEVNET_RPC_URLS = 'https://first.test,https://second.test'; const requests: string[] = []; const fetchImpl: typeof fetch = async (input, init) => { const method = JSON.parse(String(init?.body)).method; requests.push(`${input}:${method}`); if (String(input).startsWith('https://first.test') && method === 'getAccountInfo' && requests.filter(x => x.endsWith('getAccountInfo')).length % 2 === 0) return new Response('', { status: 503 }); return f.fetchImpl(input, init); }; try { const report = await readReport(f.poolAddress, 'devnet', { fetchImpl }); assert.deepEqual(requests.map(x => x.split(':get')[0]), ['https://first.test','https://first.test','https://first.test','https://first.test','https://second.test','https://second.test','https://second.test']); assert.equal((report.raw as Record<string, unknown>).rpcEndpointIndex, 1); assert.equal(report.coverage, 100); } finally { if (previous === undefined) delete process.env.DEVNET_RPC_URLS; else process.env.DEVNET_RPC_URLS = previous; } });
test('invalid accounts are not retried or reclassified as infrastructure failure', async () => { const f = await fixture(); const previous = process.env.DEVNET_RPC_URLS; process.env.DEVNET_RPC_URLS = 'https://first.test,https://second.test'; f.accounts.set(f.poolAddress, null); let count = 0; try { await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl: async (input, init) => { count++; return f.fetchImpl(input, init); } }), InvalidAccountError); assert.equal(count, 1); } finally { if (previous === undefined) delete process.env.DEVNET_RPC_URLS; else process.env.DEVNET_RPC_URLS = previous; } });
test('RPC helper retries429 but does not retry non-transient400', async () => { let count = 0; const fetchImpl: typeof fetch = async () => ++count === 1 ? new Response('', { status: 429 }) : new Response(JSON.stringify({ result: { ok: true } })); assert.deepEqual(await rpcCall('getVersion', [], 'devnet', { fetchImpl }), { ok: true }); assert.equal(count, 2); count = 0; await assert.rejects(() => rpcCall('getVersion', [], 'devnet', { fetchImpl: async () => { count++; return new Response('', { status: 400 }); } }), /400/); assert.equal(count, 1); });
test('fallback attempts share a global deadline and stop actual fetch on cancellation', async () => { const previous = process.env.DEVNET_RPC_URLS; process.env.DEVNET_RPC_URLS = 'https://first.test,https://second.test'; let count = 0; let active = 0; const fetchImpl: typeof fetch = async (_input, init) => { count++; active++; return new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => { active--; reject(init.signal!.reason); }, { once: true })); }; const keepAlive = setInterval(() => {}, 1000); try { await assert.rejects(() => rpcCall('getVersion', [], 'devnet', { fetchImpl, timeoutMs: 40, totalTimeoutMs: 15 }), /timeout|aborted/i); assert.equal(count, 1); assert.equal(active, 0); } finally { clearInterval(keepAlive); if (previous === undefined) delete process.env.DEVNET_RPC_URLS; else process.env.DEVNET_RPC_URLS = previous; } });
test('timeout while reading response body after headers retries the transport', async () => { let count = 0; const fetchImpl: typeof fetch = async (_input, init) => { if (++count > 1) return new Response(JSON.stringify({ result: 'recovered' })); return new Response(new ReadableStream({ start(controller) { init?.signal?.addEventListener('abort', () => controller.error(init.signal!.reason), { once: true }); } })); }; const keepAlive = setInterval(() => {}, 1000); try { assert.equal(await rpcCall('getVersion', [], 'devnet', { fetchImpl, timeoutMs: 15 }), 'recovered'); assert.equal(count, 2); } finally { clearInterval(keepAlive); } });
test('oversized streaming body is not retried as a transport timeout', async () => { let count = 0; const fetchImpl: typeof fetch = async () => { count++; return new Response(new ReadableStream({ start(controller) { controller.enqueue(new Uint8Array(1_048_577)); controller.close(); } })); }; await assert.rejects(() => rpcCall('getVersion', [], 'devnet', { fetchImpl }), /too large/); assert.equal(count, 1); });
test('transient mint failure restarts complete snapshot and falls back before returning unknown', async () => { const f = await fixture(); const previous = process.env.DEVNET_RPC_URLS; process.env.DEVNET_RPC_URLS = 'https://first.test,https://second.test'; const calls: string[] = []; const fetchImpl: typeof fetch = async (input, init) => { const request = JSON.parse(String(init?.body)); calls.push(`${input}:${request.method}`); if (String(input).startsWith('https://first.test') && request.method === 'getMultipleAccounts') return new Response('', { status: 503 }); return f.fetchImpl(input, init); }; try { const report = await readReport(f.poolAddress, 'devnet', { fetchImpl }); assert.equal(report.coverage, 100); assert.equal((report.raw as Record<string, unknown>).rpcEndpointIndex, 1); assert.equal(calls.length, 9); assert.equal((report.raw as Record<string, unknown>).mintReadError, null); } finally { if (previous === undefined) delete process.env.DEVNET_RPC_URLS; else process.env.DEVNET_RPC_URLS = previous; } });
test('caller cancellation after a partial snapshot does not return stale partial success', async () => { const f = await fixture(); const controller = new AbortController(); let mintCalls = 0; const fetchImpl: typeof fetch = async (input, init) => { if (JSON.parse(String(init?.body)).method === 'getMultipleAccounts' && ++mintCalls === 1) { controller.abort(new Error('Cancelled after partial read')); throw new Error('RPC offline'); } return f.fetchImpl(input, init); }; await assert.rejects(() => readReport(f.poolAddress, 'devnet', { fetchImpl, signal: controller.signal }), /Cancelled/); });
test('shared scheduler spaces requests, bounds waiting queue and removes aborted entries', async () => { const scheduler = new RpcScheduler(20, 1); await scheduler.acquire(new AbortController().signal); const controller = new AbortController(); const queued = scheduler.acquire(controller.signal); assert.equal(scheduler.pending, 1); await assert.rejects(() => scheduler.acquire(new AbortController().signal), /busy/); controller.abort(new Error('Queued client cancelled')); await assert.rejects(() => queued, /cancelled/); assert.equal(scheduler.pending, 0); const before = Date.now(); await scheduler.acquire(new AbortController().signal); assert.ok(Date.now() - before >= 35); });
test('queued fetch cancellation never dispatches an upstream request', async () => { const scheduler = new RpcScheduler(10); let count = 0; const fetchImpl: typeof fetch = async () => { count++; return new Response('ok'); }; await boundedFetch('https://queue.test', {}, { scheduler, fetchImpl }); const controller = new AbortController(); const queued = boundedFetch('https://queue.test', {}, { scheduler, fetchImpl, signal: controller.signal }); controller.abort(new Error('Cancelled in queue')); await assert.rejects(() => queued, /queue/); assert.equal(count, 1); assert.equal(scheduler.pending, 0); });
test('cooldown delays queued work and Retry-After parses seconds/dates with bounded maximum', async () => { const scheduler = new RpcScheduler(100); const before = Date.now(); scheduler.cooldown(70); await scheduler.acquire(new AbortController().signal); assert.ok(Date.now() - before >= 60); assert.equal(retryAfterSeconds('300'), 10); assert.equal(retryAfterSeconds('3'), 3); assert.equal(retryAfterSeconds('nonsense'), 1); assert.ok(retryAfterSeconds(new Date(Date.now() + 5000).toUTCString()) >= 4); });
test('429 cools down other queued clients and preserves final HTTP metadata', async () => { const scheduler = new RpcScheduler(100); const starts: number[] = []; const fetchImpl: typeof fetch = async () => { starts.push(Date.now()); return new Response('', { status: 429, headers: { 'retry-after': '1' } }); }; await assert.rejects(() => rpcCall('getVersion', [], 'devnet', { scheduler, fetchImpl, retryDelayMs: 0 }), (error: unknown) => error instanceof RpcTransportError && error.status === 429 && error.retryAfter === 1); assert.equal(starts.length, 2); assert.ok(starts[1] - starts[0] >= 900); });
test('asynchronous retry backoff allows cancellation before dispatching a retry', async () => { let count = 0; const controller = new AbortController(); const fetchImpl: typeof fetch = async () => { count++; setTimeout(() => controller.abort(new Error('Stop retry backoff')), 10); return new Response('', { status: 503 }); }; await assert.rejects(() => rpcCall('getVersion', [], 'devnet', { fetchImpl, signal: controller.signal }), /backoff/); assert.equal(count, 1); });
test('eight simultaneous inspections share one bounded transport scheduler', async () => { const f = await fixture(); const scheduler = new RpcScheduler(100); const starts: number[] = []; const fetchImpl: typeof fetch = async (input, init) => { starts.push(Date.now()); return f.fetchImpl(input, init); }; const reports = await Promise.all(Array.from({ length: 8 }, () => readReport(f.poolAddress, 'devnet', { scheduler, fetchImpl, totalTimeoutMs: 2000 }))); assert.equal(reports.length, 8); assert.equal(starts.length, 24); assert.ok(starts.at(-1)! - starts[0] >= 200); assert.equal(scheduler.pending, 0); assert.ok(reports.every(report => report.coverage === 100)); });
test('official mainnet and devnet share default public two-request-per-second gate', async () => { const previousFetch = globalThis.fetch; const previousRate = process.env.RPC_REQUESTS_PER_SECOND; delete process.env.RPC_REQUESTS_PER_SECOND; const starts: number[] = []; globalThis.fetch = async () => { starts.push(Date.now()); return new Response('ok'); }; try { await Promise.all([boundedFetch('https://api.mainnet-beta.solana.com'), boundedFetch('https://api.devnet.solana.com')]); assert.equal(starts.length, 2); assert.ok(starts[1] - starts[0] >= 450); } finally { globalThis.fetch = previousFetch; if (previousRate !== undefined) process.env.RPC_REQUESTS_PER_SECOND = previousRate; } });
test('eight real reader flows fit the default public scheduler and production deadline without external requests', async () => { const f = await fixture(); const previousFetch = globalThis.fetch; const previousRate = process.env.RPC_REQUESTS_PER_SECOND; delete process.env.RPC_REQUESTS_PER_SECOND; let calls = 0; globalThis.fetch = async (input, init) => { calls++; return f.fetchImpl(input, init); }; const before = Date.now(); try { const reports = await Promise.all(Array.from({ length: 8 }, () => readReport(f.poolAddress, 'devnet', { totalTimeoutMs: 16000 }))); assert.equal(calls, 24); assert.ok(Date.now() - before >= 11000); assert.ok(Date.now() - before < 16000); assert.ok(reports.every(report => report.coverage === 100)); } finally { globalThis.fetch = previousFetch; if (previousRate !== undefined) process.env.RPC_REQUESTS_PER_SECOND = previousRate; } });
test('explicit global deadline interrupts a long Retry-After without weak timeout signal retention', async () => { let attempts = 0; const before = Date.now(); await assert.rejects(() => withRpcRetries('devnet', { totalTimeoutMs: 30 }, async () => { attempts++; throw new RpcTransportError('RPC busy', true, 429, 10); }), /timed out/); assert.equal(attempts, 1); assert.ok(Date.now() - before < 500); });
test('explicit queue deadline cancels cooldown wait before any upstream fetch', async () => { const scheduler = new RpcScheduler(2); scheduler.cooldown(10000); let calls = 0; const before = Date.now(); await assert.rejects(() => boundedFetch('https://queue.test', {}, { scheduler, totalTimeoutMs: 30, fetchImpl: async () => { calls++; return new Response('unexpected'); } }), /timed out/); assert.equal(calls, 0); assert.equal(scheduler.pending, 0); assert.ok(Date.now() - before < 500); });
