import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { Report } from './types';
import { demo } from './demo';
import { InspectionRequest, REAL_POOL, recommendations, statusCounts } from './report-tools';
import './style.css';

const params = new URLSearchParams(location.search);
const short = (value: string) => value.length > 24 ? `${value.slice(0, 8)}…${value.slice(-8)}` : value;
function download(name: string, data: Blob) { const url = URL.createObjectURL(data); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function App() {
  const [address, setAddress] = useState(params.get('pool') || '');
  const [network, setNetwork] = useState<Report['network']>(params.get('network') === 'devnet' ? 'devnet' : 'mainnet-beta');
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const request = useRef(new InspectionRequest());
  useEffect(() => () => request.current.cancel(), []);
  function reset() { request.current.cancel(); setLoading(false); setReport(null); setError(''); setNotice(''); }
  async function inspect(pool = address.trim(), cluster = network) {
    const current = request.current.start(); setLoading(true); setError(''); setReport(null); setNotice('');
    try {
      const response = await fetch(`/api/inspect?address=${encodeURIComponent(pool)}&network=${cluster}`, { signal: AbortSignal.any([current.signal, AbortSignal.timeout(55000)]) });
      const body = await response.json();
      if (!current.isCurrent()) return;
      if (!response.ok) throw new Error(body.error || 'Inspection failed.');
      if (body.address !== pool || body.network !== cluster || body.synthetic !== false) throw new Error('Unexpected inspection response. Please retry.');
      setReport(body); history.replaceState(null, '', `?pool=${encodeURIComponent(pool)}&network=${cluster}`);
    } catch (e) { if (current.isCurrent() && !current.signal.aborted) setError((e as Error).name === 'TimeoutError' ? 'Inspection timed out. Please retry shortly.' : (e as Error).message); }
    finally { if (current.isCurrent()) setLoading(false); }
  }
  function run(event: React.FormEvent) { event.preventDefault(); void inspect(); }
  async function share() { if (!report || report.synthetic) return; const link = `${location.origin}${location.pathname}?pool=${report.address}&network=${report.network}`; try { await navigator.clipboard.writeText(link); setNotice('Inspection link copied. Recipients can run a fresh inspection.'); } catch { setNotice(link); } }
  function card() { if (!report) return; const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 630; const ctx = canvas.getContext('2d'); if (!ctx) return; const counts = statusCounts(report); ctx.fillStyle = '#fafaf3'; ctx.fillRect(0, 0, 1200, 630); ctx.fillStyle = '#1a1a1a'; ctx.font = '24px monospace'; ctx.fillText(`DBC GUARD / ${report.synthetic ? 'SYNTHETIC DEMO' : report.network.toUpperCase()}`, 64, 80); let size = 56; do { ctx.font = `bold ${size}px sans-serif`; size--; } while (ctx.measureText(report.verdict).width > 1072 && size > 24); ctx.fillText(report.verdict, 64, 190); ctx.font = '24px monospace'; ctx.fillText(`${report.coverage}% check coverage`, 64, 250); ctx.fillText(`${counts.risk} risks · ${counts.caution} cautions · ${counts.unknown} unknown`, 64, 290); ctx.font = '22px monospace'; ctx.fillText(report.address, 64, 350); ctx.fillText(`Inspected ${new Date(report.inspectedAt).toISOString()}`, 64, 400); ctx.fillText(`Slot ${report.slot ?? 'N/A — synthetic'}`, 64, 440); ctx.font = '20px sans-serif'; ctx.fillText('Snapshot assessment. No flagged issues does not establish safety.', 64, 535); ctx.fillText('8 transparent checks · Meteora Dynamic Bonding Curve', 64, 575); canvas.toBlob(blob => blob && download('dbc-guard-card.png', blob)); }
  return <><header><a className="brand" href="/">DBC<span>GUARD</span><i>↗</i></a><span className="meta">METEORA / INDEPENDENT TOOL</span><a href="#methodology">Methodology ↘</a></header><main>
    <section className="hero"><div className="eyebrow"><span className="dot"/> READ-ONLY ON-CHAIN INSPECTION</div><h1>Know the curve.<br/><span>See the exposure.</span></h1><p className="intro">Eight transparent checks for Meteora DBC pools.<br/>Real accounts. Explicit evidence. No wallet required.</p>
      <form onSubmit={run} aria-busy={loading}><label htmlFor="address">DBC POOL ADDRESS</label><div className="inputRow"><input id="address" value={address} onChange={e => { reset(); setAddress(e.target.value); }} placeholder="Paste a pool address, not a token mint" required maxLength={44} autoComplete="off" spellCheck={false}/><select aria-label="Solana network" value={network} onChange={e => { reset(); setNetwork(e.target.value as Report['network']); }}><option value="mainnet-beta">Mainnet</option><option value="devnet">Devnet</option></select><button disabled={loading}>{loading ? 'Inspecting…' : 'Inspect pool ↗'}</button></div></form>
      <div className="helper"><span>Confirmed chain reads · No transactions</span><button className="textButton" onClick={() => { reset(); setAddress(REAL_POOL); setNetwork('mainnet-beta'); void inspect(REAL_POOL, 'mainnet-beta'); }}>Inspect real mainnet example →</button><button className="textButton" onClick={() => { reset(); setAddress(demo.address); setNetwork(demo.network); setReport({ ...demo, inspectedAt: new Date().toISOString() }); }}>Explore synthetic demo →</button></div>
      {loading && <div className="message" role="status">Reading the pool, configuration and token mints. This may take up to 50 seconds. <button className="textButton" onClick={reset}>Cancel inspection</button></div>}{error && <div className="message error" role="alert">{error} <button className="textButton" onClick={() => void inspect()}>Retry inspection</button></div>}
    </section>
    {report && <section className="results" aria-label="Inspection report"><div className="reportHeading"><div><div className="eyebrow">{report.synthetic ? 'SYNTHETIC DEMO / NOT CHAIN DATA' : `${report.network.toUpperCase()} / SLOT ${report.slot}`}</div><h2>{report.verdict}</h2><p>{report.checks.filter(c => c.status === 'risk').length} risk flags · {report.checks.filter(c => c.status === 'caution').length} cautions · {report.checks.filter(c => c.status === 'unknown').length} unknown · {report.checks.filter(c => c.status !== 'unknown').length}/8 checks available</p><p>No flagged issues does not establish safety. Unchecked risks remain.</p></div><div className="coverage"><strong>{report.coverage}<small>%</small></strong><span>CHECK COVERAGE</span></div></div>
      <div className="reportMeta"><span title={report.address}>POOL {short(report.address)}</span><span>{new Date(report.inspectedAt).toLocaleString()}</span><div className="actions"><button className="textButton" onClick={() => download('dbc-guard-report.json', new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' }))}>JSON ↓</button><button className="textButton" onClick={card}>Card PNG ↓</button>{!report.synthetic && <button className="textButton" onClick={share}>Share ↗</button>}</div></div>{notice && <p role="status" className="notice">{notice}</p>}
      <div className="migration"><div><span className="eyebrow">GRADUATION PROGRESS</span><h3>{report.migration.percent.toFixed(2)}<small>%</small></h3></div><div className="migrationTrack"><progress aria-label="Graduation progress" max="100" value={report.migration.percent}/><p>{report.migration.reserve} / {report.migration.threshold} quote tokens</p><span>{report.migration.status} → {report.migration.destination}</span></div></div>
      <div className="checks">{report.checks.map((check, i) => <article className={`check ${check.status}`} key={check.id}><div className="checkTop"><span className="meta">0{i + 1}</span><span className="badge">{check.status === 'pass' ? 'No flag' : check.status === 'risk' ? 'Known risk' : check.status}</span></div><h3>{check.title}</h3><p>{check.summary}</p>{check.recommendation && <p className="recommendation">↗ {check.recommendation}</p>}<details><summary>View evidence</summary><dl>{Object.entries(check.evidence).map(([key, value]) => <React.Fragment key={key}><dt>{key}</dt><dd>{Array.isArray(value) ? value.join(', ') || 'None' : String(value)}</dd></React.Fragment>)}</dl></details></article>)}</div>
      {!report.synthetic && <div className="accountLinks">{[['Pool', report.address], ['Config', report.configAddress], ['Base mint', report.mintAddress], ['Quote mint', report.quoteMint], ['Creator', report.creator]].map(([label, key]) => <a key={label} href={`https://explorer.solana.com/address/${key}?cluster=${report.network}`} target="_blank" rel="noreferrer">{label} ↗</a>)}</div>}
      <button className="secondary" onClick={() => download('dbc-guard-recommendations.json', new Blob([JSON.stringify(recommendations(report), null, 2)], { type: 'application/json' }))}>Export review recommendations ↓</button>
    </section>}
    <section className="methodology" id="methodology"><span className="eyebrow">HOW TO READ THE REPORT</span><h2>Evidence first.<br/>Certainty never assumed.</h2><div className="methodGrid"><div><h3>01 / What we read</h3><p>Pool and config account ownership and SDK discriminators, token mint authorities and extension types, configured fees, LP allocation, creator vesting, curve boundaries and migration state.</p></div><div><h3>02 / How we flag</h3><p>Mint or freeze capability and majority unlocked LP receive risk flags. Fee ceilings above 3% receive caution; above 10% receive risk. Creator allocation above 20% and graduation price amplification above 100× are review heuristics.</p></div><div><h3>03 / What stays unknown</h3><p>Holder distribution, creator identity, linked wallets, code exploits, extension parameters, quote-token safety and post-migration liquidity positions are not audited. Reads are confirmed snapshots, not one atomic state.</p></div></div><p className="fineprint">Coverage counts available checks, not percentage of security audited. Configured locks describe migration allocation, not verified current DAMM positions. Reports do not certify safety or predict price. DBC Guard cannot change deployed pool configurations.</p></section>
  </main><footer><span>DBC GUARD</span><span>BUILT FOR METEORA DBC · SDK 1.5.13</span><a href="https://docs.meteora.ag/developer-guides/dbc" target="_blank" rel="noreferrer">Protocol documentation ↗</a></footer></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
